### ISSUE TITLE
log4j-search issue in script

### ISSUE THREAD

**Issue by midiman1000** [isaacatmann/log4j-search#1]
Hello isaacatman,

Thanks for the hard work on this script, I'm getting a "bad substitution" on line 41 still I fixed the line 36 & 38 with quotes around the eaCache.

I've look at many solutions for line 41 but nothing is working, thought you might have some time to look at this.

Thank you,

**Comment by midiman1000** [comment]
Forget the issue as I figured it and again many thx!!

**Comment by isaacatmann** [comment]
You're welcome @midiman1000 !
